/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import Util.ConnectionFactory;
import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import model.Task;

public class App {
   
    public static void main(String[] args) {
        
        ProjectController pControl = new ProjectController();
        TaskController tControl = new TaskController();
//        tControl.removeById(6);
//        tControl.removeById(7);
//        tControl.removeById(10);
//        
//        pControl.removeById(4);
//        pControl.removeById(5);
        
//        Project project = new Project();
//        project.setName("Meu primeiro projeto");
//        project.setDescription("description");
//        pControl.save(project);
//        
//         Project project2 = new Project();
//        project2.setName("Meu segundo projeto");
//        project2.setDescription("description");
//        pControl.save(project2);
        
//          Task task = new Task();
//          task.setName("Tarefa 3");
//          task.setId(2);
//          task.setIdProject(2);
//          task.setCompleted(Boolean.TRUE);
//          tControl.update(task);
//          task.setIdProject(2);
//          task.setCompleted(Boolean.FALSE);
//          tControl.save(task);
          
          Task task = new Task();
          task.setName("Primeira tarefa");
          task.setIdProject(6);
          task.setCompleted(Boolean.FALSE);
          tControl.save(task);
          
          Task task1 = new Task();
          task1.setName("Segunda tarefa");
          task1.setIdProject(6);
          task1.setCompleted(Boolean.FALSE);
          tControl.save(task1);
          
          Task task2 = new Task();
          task2.setName("Terceira tarefa");
          task2.setIdProject(6);
          task2.setCompleted(Boolean.FALSE);
          tControl.save(task2);
//          


//         Task task = new Task();
//         task.setName("Tarefa 1");
//         task.setIdProject(2);
//         task.setCompleted(Boolean.FALSE);
//         tControl.save(task);

//         Task task2 = new Task();
//         task2.setName("Tarefa 2");
//         task2.setIdProject(2);
//         task2.setCompleted(Boolean.FALSE);
//         tControl.save(task2);
//
//          Task task3 = new Task();
//          task2.setName("Tarefa 3");
//          task2.setIdProject(2);
//          task2.setCompleted(Boolean.FALSE);
//          tControl.save(task3);

// List<Task> tasks = tControl.getAll(2);
//// 
// 
//     System.out.println(tasks.size());
// 
        

//          tControl.removeById(1);
//        pControl.update(project);    
//          List<Project> projects = pControl.getAll();
          System.out.println("Total: " + pControl.getAll().size() );
//          pControl.removeById(1);
//      Connection connection = ConnectionFactory.getConnection();
//      ConnectionFactory.closeConnection(connection);
    }
}
